### ISSUE TITLE
ObserverHealthReporter does not support all available health report types needed for fabric observer plugins

### ISSUE THREAD

**Issue by adamtickner** [microsoft/service-fabric-observer#85] opened 2020-11-09 02:53 UTC
Hi

I'd like to have some more flexibility with health reporting options whilst utilising the existing health reporter class.

PR will add the types from here except cluster health reporting as there is a separate Cluster Observer app that handles that level of information: https://docs.microsoft.com/en-us/dotnet/api/system.fabric.health.healthreport?view=azure-dotnet

Thanks, Adam

**Comment by GitTorre** [comment] 2020-11-09 19:13
This is by design. FO supports Application and Node health reports (for Node, they are VM-level, Application covers Services (which will contain partition and replicas/instance info as part of the TelemetryData instances). If you want to extend this capability for reporting purposes without affecting other parts of the system, you would do this as part of your plugin. ObserverHealthReporter is a small, simple class. You should simply extend it in your own impl and use your version in your plugin codebase, not FO's.

Are you using ObserverBase.ProcessResourceDataReportHealth function in your plugin? Or, are you just using ObserverHealthReporter to generate health reports? I don't think FO should support a bunch of health report types when their are two types the system has been designed to support for a reason. The idea of plugins is that you can do whatever you want, whatever makes sense for your needs, outside of the base FO impl.

Let me know if I am misunderstanding your needs. The health reporting system is confusing (SF) given the number of kinds and evaluations, and types. For FO, you have built-in observers that report on Application health (an application is composed of one or more services) and VM (as Node health reports) with respect to resource usage. The relevant information is surfaced as members (properties) of a TelemetryData instance that is serialized as part of the higher level (Application) health report's Description. If your plugin is designed to monitor replica health or partition health, then your observer can generate the types of reports required for your scenario. No other observer in the system would leverage your changes. I don't think it merits a change in the core impl.

...Charles

**Comment by GitTorre** [comment] 2020-11-09 21:58
The change seems benign enough to me. I made a minor change to your PR. There is no need to have InstanceId and ReplicaId. They are both longs and in our platform, we opt for ReplicaOrInstanceId to reflect stateful versus stateless instance ids (replica or instance).

**Comment by adamtickner** [comment] 2020-11-09 22:17
Thanks Charles.

I'm not using ProcessResourceDataReportHealth  at the moment as I was using the network observer as an example which uses the ObserverHealthReporter.

Having looked at the source code for ProcessResourceDataReportHealth I can see that won't handle these new cases - would you like any changes made in there so it reports correctly on these new report types?

In case it helps (please let me know if this sounds like the wrong use case), I am trying to do the following:

- Build a HealthCheckObserver to check any .net core health checks (so devs can just implement health checks in the apps and have service fabric reporting work automatically)
- These could be various types of service fabric service
- Set health status on the correct instance/node they are running on 

I am wondering if that last point is correct - would you normally expect an application to be in warning if one instance is unhealthy? 

Appreciate your help and input!

**Comment by GitTorre** [comment] 2020-11-09 22:38
Hi,

I am not sure I understand the scenario. 

For ProcessResourceDataReportHealth, the function can only operate on numeric data (so, FRUD instances (FabricResourceUsageData type) that hold either List<T> or CircularBufferCollection<T> types). It is only useful when an observer is collecting machine resource usage metric data (like memory use, or CPU use, or port count, or disk space or..). It not useful for other types of data processing (and cannot work outside of what it is intended to be used for). So, there is no work to be done in this function to support your scenario, which is not resource usage based. 

When a service of an application exceeds supplied memory use threshold, for example, then it is certainly the right thing to do to put the Application in Warning (or Error, depending upon your configuration settings for application (or application type) as it relates to some observable resource metric). 

Can you elaborate a bit more on what you are trying to achieve with your plugin?

Thanks!
...Charles

**Comment by adamtickner** [comment] 2020-11-09 22:54
Sorry, think I may have confused the matter by mentioning ProcessResourceDataReportHealth and the plugin in the same comment.

With the ProcessResourceDataReportHealth function I just wanted to check the PR did not need to take anything else into account.

For the plugin I am writing, it is similar to the network observer in that it will make requests but specifically in this case it will be to all of our services running on that same node and then set the health status based on the response. The network observer doesn't quite achieve this as I need a bit more control over the logic. Each application can then implement their specific health requirements in the application code with IHealthCheck and the observer will handle setting the health status based on the results. 

From the observer perspective, it is just looping over the results from FabricClientInstance.QueryManager.GetDeployedApplicationListAsync and then FabricClientInstance.QueryManager.GetDeployedReplicaListAsync, making a request to /health and then setting health of the services based on the response.

Hope I've explained that properly!

**Comment by GitTorre** [comment] 2020-11-09 23:36
Hi,

Your changes have no impact on the function unless another customer assumes that since ObserverHealthReporter supports multiple health reports types, so to do the other core impls that don't, in fact. This is why I am being conservative with respect to changing core functionality to solve a problem for a single plugin, scenario. 

Is there a reason why you don't just write your own version of ObserverHealthReporter (and also the report type enum for your needs) for your observer? It's a small impl and easy to do, as you now know. 

Thanks for the details about your observer. It makes good sense.

...Charles

**Comment by adamtickner** [comment] 2020-11-10 03:34
My issue at the moment is really that we are likely to have more than one plugin and I have no way to share code between plugins.

I might have missed something but I could not seem to use any shared projects and get it to work with plugins as the secondary DLL is not loaded. 

The effect of this is that I would have to have the same custom health reporter logic in every single plugin, so I was thinking that extending the base functionality might make this a little easier.

Are there any other ways around this?

**Comment by GitTorre** [comment] 2020-11-10 17:59
Hi Adam,

I understand. Let me spend some time on incorporating your changes and ensure meaningful failures for others when they assume there is support in shared functionality for more than App and Node health report types. I don't want you to have to work to hard on getting your scenario to work and I realize the .NET Core plugin model can be hard to figure out with respect to shared libs. It's certainly possible, but as I mentioned your changes are mostly benign. Give me some time to evaluate the behavior of code that expects health report types, make whatever changes I need to, test, then will be back in touch. Sound good?

**Comment by GitTorre** [comment] 2020-11-10 19:47
Merged PR with some additions. Will ship in 3.0.10. Should be out today. 

Thanks again for using FO and providing changes!

...Charles

**Closed by GitTorre** 2020-11-10 19:47 UTC

**Comment by adamtickner** [comment] 2020-11-10 21:15
Great - thank you!
